import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
process.on('uncaughtException', e => { console.error(e.message, e.detail || '', e.where || ''); process.exit(1); });
await db.exec(`
CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE PUBLICATION supabase_realtime;
CREATE SCHEMA auth; CREATE SCHEMA storage;
GRANT USAGE ON SCHEMA auth TO anon,authenticated,service_role;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_setting('request.jwt.claim.role',true) $$;
CREATE TABLE auth.users(id uuid PRIMARY KEY, email text, raw_user_meta_data jsonb DEFAULT '{}', created_at timestamptz DEFAULT now());
CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
CREATE TABLE storage.objects(id uuid DEFAULT gen_random_uuid(),bucket_id text,name text,owner uuid);
CREATE FUNCTION storage.foldername(text) RETURNS text[] LANGUAGE sql AS $$ SELECT string_to_array($1,'/') $$;
`);
const migrations = fs.readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort();
for (const file of migrations) {
  try { await db.exec(fs.readFileSync(`supabase/migrations/${file}`, 'utf8')); }
  catch (e) { console.error(`Migration failed: ${file}: ${e.message}`); process.exit(1); }
}
console.log('All real migrations applied successfully');
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const admin=id(1), agent=id(2), customerUser=id(3), customer=id(4), branch=id(5), main=id(6), secondary=id(7), product=id(8), retail=id(9), wholesale=id(10);
await db.exec(`
  INSERT INTO auth.users(id,email) VALUES('${admin}','admin@test.local'),('${agent}','agent@test.local'),('${customerUser}','customer@test.local');
  UPDATE public.user_profiles SET user_type='ADMIN' WHERE auth_user_id='${admin}';
  UPDATE public.user_profiles SET user_type='AGENT',agent_functions=ARRAY['SALESPERSON']::public.agent_function_type[] WHERE auth_user_id='${agent}';
  SELECT set_config('request.jwt.claim.sub','${admin}',false);
  INSERT INTO public.customers(id,auth_user_id,name,email,phone) VALUES('${customer}','${customerUser}','Test customer','client@test.local','123');
  INSERT INTO public.customer_branches(id,customer_id,name,phone_primary) VALUES('${branch}','${customer}','Test branch','123');
  INSERT INTO public.warehouses(id,code,name) VALUES('${main}','MAIN','Principal'),('${secondary}','SECOND','Secundario');
  INSERT INTO public.products(id,code,name) VALUES('${product}','TEST','Pieza');
  INSERT INTO public.price_lists(id,code,name) VALUES('${retail}','PUBLIC','Público'),('${wholesale}','WHOLESALE','Mayoreo');
  INSERT INTO public.product_prices(product_id,price_list_id,amount) VALUES('${product}','${retail}',180),('${product}','${wholesale}',160);
`);
const scalar = async sql => Object.values((await db.query(sql)).rows[0])[0];
const quantity = warehouse => scalar(`SELECT quantity FROM public.product_inventory WHERE product_id='${product}' AND warehouse_id='${warehouse}' AND location_id IS NULL`);
const fails = async (sql, regex) => {
  await assert.rejects(db.exec(sql),regex);
};
await db.exec(`SELECT public.receive_inventory('${product}','${main}','PURCHASE',10,100);`);
assert.equal(Number(await quantity(main)),10,'a purchase is applied only once');
const transfer=id(11);
await db.exec(`INSERT INTO public.inventory_transfers(id,transfer_number,source_warehouse_id,destination_warehouse_id) VALUES('${transfer}','TEST-TRANSFER','${main}','${secondary}');
INSERT INTO public.inventory_transfer_items(transfer_id,product_id,quantity,unit_price) VALUES('${transfer}','${product}',5,130);
SELECT public.process_inventory_transfer('${transfer}');`);
assert.equal(Number(await quantity(main)),5);
assert.equal(Number(await quantity(secondary)),5);
assert.equal(Number(await scalar(`SELECT amount FROM public.product_prices WHERE product_id='${product}' AND price_list_id='${retail}'`)),180,'transfer does not overwrite retail price');
await fails(`SELECT public.process_inventory_transfer('${transfer}')`,/borrador/);
await fails(`UPDATE public.inventory_transfer_items SET unit_price=150 WHERE transfer_id='${transfer}'`,/borrador/);
const payload = list => ({customer_id:customer,branch_id:branch,warehouse_id:secondary,price_list_id:list,payment_type:'CONTADO',items:[{product_id:product,quantity:2,unit_price:999}]});
await db.exec(`SELECT set_config('request.jwt.claim.sub','${agent}',false); SET ROLE authenticated;`);
const order=await scalar(`SELECT (public.create_priced_order('${JSON.stringify(payload(retail))}'::jsonb)).id`);
assert.equal(Number(await scalar(`SELECT unit_price FROM public.sales_order_items WHERE order_id='${order}'`)),180,'server reads the selected price list');
await db.exec(`UPDATE public.sales_orders SET status='SHIPPED' WHERE id='${order}'; UPDATE public.sales_orders SET status='DELIVERED' WHERE id='${order}';`);
assert.equal(Number(await quantity(secondary)),3,'shipping and delivery discount stock once');
assert.equal((await db.query('SELECT * FROM public.sales_item_costs')).rows.length,0,'agents cannot read costs');
assert.equal((await db.query('SELECT * FROM public.sales_margins')).rows.length,0,'agents cannot read margins');
await fails(`SELECT public.receive_inventory('${product}','${main}','PURCHASE',10,100)`,/administradores/);
await fails(`UPDATE public.sales_order_items SET quantity=3 WHERE order_id='${order}'`,/modificar/);
await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${admin}',false);`);
const margins=(await db.query(`SELECT * FROM public.sales_margins WHERE order_id='${order}'`)).rows[0];
assert.equal(Number(margins.warehouse_margin),100);
assert.equal(Number(margins.upstream_margin),60);
assert.equal(Number(margins.gross_profit),160);
await db.exec(`SELECT public.receive_inventory('${product}','${secondary}','PURCHASE',3,200);`);
assert.equal(Number(await scalar(`SELECT gross_profit FROM public.sales_margins WHERE order_id='${order}'`)),160,'new costs do not rewrite old margins');
await db.exec(`UPDATE public.sales_orders SET status='CANCELLED' WHERE id='${order}'; UPDATE public.sales_orders SET status='CANCELLED' WHERE id='${order}';`);
assert.equal(Number(await quantity(secondary)),8,'cancel returns stock only once');
assert.equal(Number(await scalar(`SELECT average_cost FROM public.inventory_valuation WHERE product_id='${product}' AND warehouse_id='${secondary}'`)),156.25,'cancel blends the original sale cost back into current stock');
assert.equal(Number(await scalar(`SELECT original_average_cost FROM public.inventory_valuation WHERE product_id='${product}' AND warehouse_id='${secondary}'`)),137.5);
assert.equal((await db.query(`SELECT * FROM public.sales_margins WHERE order_id='${order}'`)).rows.length,0);
const wholesaleOrder=await scalar(`SELECT (public.create_priced_order('${JSON.stringify(payload(wholesale))}'::jsonb)).id`);
assert.equal(Number(await scalar(`SELECT unit_price FROM public.sales_order_items WHERE order_id='${wholesaleOrder}'`)),160);
await db.exec(`UPDATE public.sales_order_items SET quantity=100 WHERE order_id='${wholesaleOrder}';`);
await fails(`UPDATE public.sales_orders SET status='SHIPPED' WHERE id='${wholesaleOrder}'`,/insuficiente/);
assert.equal(Number(await quantity(secondary)),8,'failed sale rolls back stock');
assert.equal(Number(await scalar(`SELECT count(*) FROM public.sales_item_costs c JOIN public.sales_order_items i ON i.id=c.item_id WHERE i.order_id='${wholesaleOrder}'`)),0,'failed sale rolls back snapshots');
const unknown=id(12);
await db.exec(`INSERT INTO public.products(id,code,name) VALUES('${unknown}','UNKNOWN','Sin costo'); SELECT public.process_inventory_movement('${unknown}','${main}','INITIAL_STOCK',3);`);
assert.equal(await scalar(`SELECT average_cost FROM public.inventory_valuation WHERE product_id='${unknown}'`),null,'missing costs stay unknown');
const orderCount=await scalar('SELECT count(*) FROM public.sales_orders');
await fails(`SELECT public.create_priced_order('${JSON.stringify({...payload(retail),items:[{product_id:unknown,quantity:1,unit_price:1}]})}'::jsonb)`,/sin precio/);
assert.equal(await scalar('SELECT count(*) FROM public.sales_orders'),orderCount,'item failure rolls back the whole order');
const transferPayload = {transfer_number: 'ATOMIC-TRANSFER',source_warehouse_id:main,destination_warehouse_id:secondary,items:[{product_id:product,quantity:1,unit_price:150}]};
const atomicTransfer=await scalar(`SELECT (public.save_inventory_transfer('${JSON.stringify(transferPayload)}'::jsonb)).id`);
await fails(`SELECT public.save_inventory_transfer('${JSON.stringify({...transferPayload,source_warehouse_id:secondary,destination_warehouse_id:main,items:[{product_id:product,quantity:999,unit_price:180}]})}'::jsonb,'${atomicTransfer}')`,/insuficiente/);
assert.equal(await scalar(`SELECT source_warehouse_id FROM public.inventory_transfers WHERE id='${atomicTransfer}'`),main,'failed edit preserves original header');
assert.equal(Number(await scalar(`SELECT quantity FROM public.inventory_transfer_items WHERE transfer_id='${atomicTransfer}'`)),1,'failed edit preserves original lines');
await fails(`SELECT public.save_inventory_transfer('${JSON.stringify({...transferPayload,transfer_number:'BAD-DUPLICATE',items:[...transferPayload.items,...transferPayload.items]})}'::jsonb)`,/repetidos/);
assert.equal(Number(await scalar(`SELECT count(*) FROM public.inventory_transfers WHERE transfer_number='BAD-DUPLICATE'`)),0,'bad create leaves no orphan header');
await db.exec(`SELECT public.save_inventory_transfer('${JSON.stringify({...transferPayload,items:[{product_id:product,quantity:2,unit_price:150}]})}'::jsonb,'${atomicTransfer}'); SELECT public.process_inventory_transfer('${atomicTransfer}');`);
assert.equal(Number(await scalar(`SELECT quantity FROM public.inventory_transfer_items WHERE transfer_id='${atomicTransfer}'`)),2,'atomic edit replaces lines');
await fails(`SELECT public.save_inventory_transfer('${JSON.stringify(transferPayload)}'::jsonb,'${atomicTransfer}')`,/borrador/);
await db.exec(`UPDATE public.warehouses SET is_active=false WHERE id='${secondary}'`);
await fails(`SELECT public.save_inventory_transfer('${JSON.stringify({...transferPayload,transfer_number:'INACTIVE'})}'::jsonb)`,/activos/);
await db.exec(`UPDATE public.warehouses SET is_active=true WHERE id='${secondary}'`);
const uncostedTransferPayload={...transferPayload,transfer_number:'UNCOSTED',items:[{product_id:unknown,quantity:1,unit_price:150}]};
const uncostedTransfer=await scalar(`SELECT (public.save_inventory_transfer('${JSON.stringify(uncostedTransferPayload)}'::jsonb)).id`);
await fails(`SELECT public.process_inventory_transfer('${uncostedTransfer}')`,/UNKNOWN/);
await db.exec(`SELECT public.set_inventory_cost((SELECT id FROM public.product_inventory WHERE product_id='${unknown}' AND warehouse_id='${main}'),50,50); SELECT public.process_inventory_transfer('${uncostedTransfer}');`);
assert.equal(Number(await scalar(`SELECT average_cost FROM public.inventory_valuation WHERE product_id='${unknown}' AND warehouse_id='${secondary}'`)),150,'configured origin cost transfers automatically');
assert.equal(Number(await scalar(`SELECT original_average_cost FROM public.inventory_valuation WHERE product_id='${unknown}' AND warehouse_id='${secondary}'`)),50,'original cost follows the transfer');
await db.exec(`SELECT set_config('request.jwt.claim.sub','${customerUser}',false); SET ROLE authenticated;`);
assert.equal((await db.query('SELECT * FROM public.sales_item_costs')).rows.length,0,'customers cannot read costs');
assert.equal((await db.query('SELECT * FROM public.inventory_movements')).rows.length,0,'customers cannot read internal movement prices');
await db.exec('RESET ROLE');
// Discounts and warranty claims use the same delivered-sale ledger.
await db.exec(`SELECT set_config('request.jwt.claim.sub','${agent}',false); SET ROLE authenticated;`);
const discountedPayload={...payload(retail),items:[{product_id:product,quantity:2,unit_price:999,discount_percent:10,discount_reason:'Acuerdo con cliente'}]};
const discountedOrder=await scalar(`SELECT (public.create_priced_order('${JSON.stringify(discountedPayload)}'::jsonb)).id`);
const discountedItem=await scalar(`SELECT id FROM public.sales_order_items WHERE order_id='${discountedOrder}'`);
assert.equal(Number(await scalar(`SELECT unit_price FROM public.sales_order_items WHERE id='${discountedItem}'`)),162);
assert.equal(Number(await scalar(`SELECT total_amount FROM public.sales_orders WHERE id='${discountedOrder}'`)),324);
await db.exec(`SELECT public.set_order_item_discount('${discountedItem}',20,'Cliente frecuente')`);
assert.equal(Number(await scalar(`SELECT total_amount FROM public.sales_orders WHERE id='${discountedOrder}'`)),288);
await fails(`SELECT public.set_order_item_discount('${discountedItem}',101,'Inválido')`,/descuento/);
await fails(`SELECT public.set_order_item_discount('${discountedItem}',10,'')`,/motivo/);
await db.exec(`SELECT public.set_order_item_discount('${discountedItem}',10,'Acuerdo'); UPDATE public.sales_orders SET status='DELIVERED' WHERE id='${discountedOrder}';`);
await fails(`SELECT public.set_order_item_discount('${discountedItem}',5,'Tarde')`,/modificar/);
const returnId=id(31), returnId2=id(32);
const evidence=`${customerUser}/${discountedOrder}/${returnId}/0.jpg`;
await db.exec(`RESET ROLE; INSERT INTO storage.objects(bucket_id,name,owner) VALUES('return-evidence','${evidence}','${customerUser}'); SELECT set_config('request.jwt.claim.sub','${customerUser}',false); SET ROLE authenticated;`);
const claimSql=`SELECT public.request_order_return('${returnId}','${discountedItem}',1,'Pieza defectuosa',ARRAY['${evidence}'])`;
const stockBeforeClaim=Number(await quantity(secondary));
await db.exec(claimSql);await db.exec(claimSql);
assert.equal(Number(await scalar(`SELECT count(*) FROM public.sales_order_returns WHERE id='${returnId}'`)),1,'retry is idempotent');
assert.equal(await scalar(`SELECT status FROM public.sales_order_returns WHERE id='${returnId}'`),'PENDING','customer claims wait for review');
await fails(`SELECT public.review_order_return('${returnId}',true,NULL)`,/Solo administradores/);
assert.equal(Number(await quantity(secondary)),stockBeforeClaim,'defective units are not returned to saleable stock');
assert.equal((await db.query('SELECT * FROM public.sales_return_costs')).rows.length,0,'customer cannot read private costs');
await fails(`SELECT public.set_order_item_discount('${discountedItem}',10,'Cliente')`,/Solo agentes/);
await fails(`SELECT public.request_order_return('${returnId2}','${discountedItem}',2,'Exceso',ARRAY['${evidence}'])`,/superior/);
await fails(`SELECT public.request_order_return('${returnId2}','${discountedItem}',1,'Sin archivo',ARRAY[]::text[])`,/evidencias/);
await fails(`SELECT public.request_order_return('${returnId2}','${discountedItem}',1,'Otro archivo',ARRAY['wrong/path.jpg'])`,/evidencia no corresponde/);
await fails(`SELECT public.request_order_return('${returnId2}',(SELECT id FROM public.sales_order_items WHERE order_id='${wholesaleOrder}'),1,'No entregado',ARRAY['${evidence}'])`,/entregados/);
await fails(`SELECT public.mark_order_paid_manually('${discountedOrder}')`,/administradores/);
await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${admin}',false); SET ROLE authenticated;`);
assert.equal(Number(await scalar(`SELECT count(*) FROM public.notifications WHERE entity_id='${returnId}'`)),1,'one notification per administrator, retries do not duplicate');
const originalCost=Number(await scalar(`SELECT original_unit_cost FROM public.sales_item_costs WHERE item_id='${discountedItem}'`));
assert.equal(Number(await scalar(`SELECT gross_profit FROM public.sales_margins WHERE order_id='${discountedOrder}'`)),324-2*originalCost,'pending claims do not reduce profit');
await fails(`SELECT public.create_priced_order('${JSON.stringify({...payload(retail),warranty_return_id:returnId,items:[{product_id:product,quantity:1,unit_price:999}]})}'::jsonb)`,/Aprueba la garantía/);
await db.exec(`SELECT public.review_order_return('${returnId}',true,'Sí procede');SELECT public.review_order_return('${returnId}',true,'Reintento');`);
assert.equal(await scalar(`SELECT status FROM public.sales_order_returns WHERE id='${returnId}'`),'APPROVED');
assert.equal(Number(await scalar(`SELECT count(*) FROM public.notifications WHERE event_key='warranty-review:${returnId}'`)),0,'administrator cannot see the private customer decision notification');
await fails(`SELECT public.review_order_return('${returnId}',false,'Cambiar resolución')`,/ya fue resuelta/);
const netProfit=Number(await scalar(`SELECT gross_profit FROM public.sales_margins WHERE order_id='${discountedOrder}'`));
assert.equal(netProfit,324-3*originalCost,'claim adds only one estimated replacement expense');
await fails(`UPDATE public.sales_orders SET status='CANCELLED' WHERE id='${discountedOrder}'`,/devoluciones/);
await db.exec(`SELECT public.mark_notifications_read((SELECT id FROM public.notifications WHERE entity_id='${returnId}'))`);
assert.ok(await scalar(`SELECT read_at FROM public.notifications WHERE entity_id='${returnId}'`));
const replacementPayload={...payload(retail),warranty_return_id:returnId,items:[{product_id:product,quantity:1,unit_price:999}]};
const replacement=await scalar(`SELECT (public.create_priced_order('${JSON.stringify(replacementPayload)}'::jsonb)).id`);
await db.exec(`SELECT public.mark_order_paid_manually('${replacement}'); SELECT public.mark_order_paid_manually('${replacement}');`);
assert.equal(Number(await scalar(`SELECT amount_paid FROM public.sales_orders WHERE id='${replacement}'`)),180,'manual paid is idempotent');
assert.equal(Number(await scalar(`SELECT count(*) FROM public.sales_order_payments WHERE order_id='${replacement}'`)),1);
await db.exec(`UPDATE public.sales_orders SET status='DELIVERED' WHERE id='${replacement}'`);
assert.equal(Number(await scalar(`SELECT count(*) FROM public.sales_margins WHERE order_id='${replacement}'`)),0,'replacement is not new revenue');
assert.equal(Number(await quantity(secondary)),stockBeforeClaim-1,'replacement consumes inventory once');
assert.equal(Number(await scalar(`SELECT gross_profit FROM public.sales_margins WHERE order_id='${discountedOrder}'`)),netProfit,'replacement dispatch does not charge the warranty twice');
await fails(`SELECT public.create_priced_order('${JSON.stringify({...replacementPayload,items:[{product_id:product,quantity:2,unit_price:999}]})}'::jsonb)`,/duplicate key|cantidad/);
await db.exec(`SELECT public.send_custom_notification(ARRAY['${admin}']::uuid[],'Aviso general','Texto libre','products','${product}','/catalog/products/${product}')`);
await fails(`SELECT public.send_custom_notification(ARRAY['${admin}']::uuid[],'Enlace inseguro','Texto','products','${product}','//example.com')`,/check constraint/);
await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${agent}',false); SET ROLE authenticated;`);
assert.equal(Number(await scalar(`SELECT count(*) FROM public.notifications`)),0,'notifications are private to each recipient');
await fails(`SELECT public.create_priced_order('${JSON.stringify(replacementPayload)}'::jsonb)`,/administradores/);
const evidence2=`${agent}/${discountedOrder}/${returnId2}/0.jpg`;
await db.exec(`RESET ROLE; INSERT INTO storage.objects(bucket_id,name,owner) VALUES('return-evidence','${evidence2}','${agent}'); SET ROLE authenticated; SELECT public.request_order_return('${returnId2}','${discountedItem}',1,'Agente registra',ARRAY['${evidence2}']);`);
assert.equal(Number(await scalar(`SELECT count(*) FROM public.sales_order_returns WHERE order_id='${discountedOrder}'`)),2,'agent claims need no approval');
assert.equal(await scalar(`SELECT status FROM public.sales_order_returns WHERE id='${returnId2}'`),'APPROVED','agent is auto-approved');
await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${customerUser}',false); SET ROLE authenticated;`);
assert.equal(Number(await scalar(`SELECT count(*) FROM public.notifications WHERE event_key='warranty-review:${returnId}'`)),1,'customer receives one approval notification');
await db.exec('RESET ROLE');
await db.exec('RESET ROLE');
await db.exec(`GRANT USAGE ON SCHEMA storage TO authenticated; GRANT SELECT,INSERT,DELETE ON storage.objects TO authenticated; ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;`);
const outsider=id(41);
await db.exec(`INSERT INTO auth.users(id,email) VALUES('${outsider}','outsider@test.local'); SELECT set_config('request.jwt.claim.sub','${outsider}',false); SET ROLE authenticated;`);
await fails(`SELECT public.request_order_return('${id(44)}','${discountedItem}',1,'Otro cliente',ARRAY['${evidence}'])`,/No tienes acceso/);
assert.equal((await db.query(`SELECT * FROM public.sales_order_returns WHERE order_id='${discountedOrder}'`)).rows.length,0,'other customers cannot see returns');
assert.equal((await db.query(`SELECT * FROM storage.objects WHERE bucket_id='return-evidence'`)).rows.length,0,'other customers cannot see evidence');
await fails(`INSERT INTO storage.objects(bucket_id,name)VALUES('return-evidence','${outsider}/${discountedOrder}/${id(44)}/0.jpg')`,/row-level security/);
await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${customerUser}',false); SET ROLE authenticated;`);
assert.equal((await db.query(`SELECT * FROM storage.objects WHERE name='${evidence}'`)).rows.length,1,'owner can open evidence');
await db.exec(`DELETE FROM storage.objects WHERE name='${evidence}'`);
assert.equal((await db.query(`SELECT * FROM storage.objects WHERE name='${evidence}'`)).rows.length,1,'attached evidence cannot be removed');
await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${admin}',false); SET ROLE authenticated;`);
assert.equal((await db.query(`SELECT * FROM storage.objects WHERE name='${evidence}'`)).rows.length,1,'administrator can open customer evidence');
await db.exec('RESET ROLE');
// Rejecting a customer claim releases its quantity for a new application.
await db.exec(`SELECT set_config('request.jwt.claim.sub','${admin}',false); SET ROLE authenticated;`);
const rejectionOrder=await scalar(`SELECT (public.create_priced_order('${JSON.stringify(payload(retail))}'::jsonb)).id`);
await db.exec(`UPDATE public.sales_orders SET status='DELIVERED' WHERE id='${rejectionOrder}'`);
const rejectionItem=await scalar(`SELECT id FROM public.sales_order_items WHERE order_id='${rejectionOrder}'`);
const rejectionId=id(50),resubmitId=id(51);
const rejectionPath=`${customerUser}/${rejectionOrder}/${rejectionId}/0.jpg`;
await db.exec(`RESET ROLE;INSERT INTO storage.objects(bucket_id,name,owner)VALUES('return-evidence','${rejectionPath}','${customerUser}');SELECT set_config('request.jwt.claim.sub','${customerUser}',false);SET ROLE authenticated;SELECT public.request_order_return('${rejectionId}','${rejectionItem}',2,'Revisión',ARRAY['${rejectionPath}']);`);
await db.exec(`RESET ROLE;SELECT set_config('request.jwt.claim.sub','${admin}',false);SET ROLE authenticated;`);
const beforeReject=await scalar(`SELECT gross_profit FROM public.sales_margins WHERE order_id='${rejectionOrder}'`);
await fails(`SELECT public.review_order_return('${rejectionId}',false,'')`,/motivo del rechazo/);
await db.exec(`SELECT public.review_order_return('${rejectionId}',false,'No corresponde a defecto');SELECT public.review_order_return('${rejectionId}',false,'Reintento');`);
assert.equal(await scalar(`SELECT gross_profit FROM public.sales_margins WHERE order_id='${rejectionOrder}'`),beforeReject,'rejections do not reduce profit');
await fails(`SELECT public.review_order_return('${rejectionId}',true,'Cambiar respuesta')`,/ya fue resuelta/);
const resubmitPath=`${customerUser}/${rejectionOrder}/${resubmitId}/0.jpg`;
await db.exec(`RESET ROLE;INSERT INTO storage.objects(bucket_id,name,owner)VALUES('return-evidence','${resubmitPath}','${customerUser}');SELECT set_config('request.jwt.claim.sub','${customerUser}',false);SET ROLE authenticated;SELECT public.request_order_return('${resubmitId}','${rejectionItem}',2,'Nueva evidencia',ARRAY['${resubmitPath}']);`);
assert.equal(await scalar(`SELECT status FROM public.sales_order_returns WHERE id='${resubmitId}'`),'PENDING','rejection releases quantity');
assert.equal(Number(await scalar(`SELECT count(*) FROM public.notifications WHERE event_key='warranty-review:${rejectionId}'`)),1,'one private rejection notification');
await db.exec('RESET ROLE');
console.log('PASS: customer approval/rejection, pending profit, released quantities, private decision notifications and agent automatic approval');
console.log('PASS: discounts, final prices, delivered-only claims, evidence, quantity limits, idempotency, private notifications, warranty expense and manual paid replacement');
console.log('PASS: purchase, transfer, retail/wholesale, margins, immutable costs, cancellation, rollback, missing costs, agent/customer permissions, atomic create/edit, duplicates, inactive warehouses, cost initialization');
await db.exec(`SELECT set_config('request.jwt.claim.sub','${admin}',false);
 INSERT INTO public.customer_fiscal_profiles(id,customer_id,rfc,legal_name,tax_regime,cfdi_use,fiscal_zip_code,billing_email)
 VALUES('${id(70)}','${customer}','TEST010101AAA','Fiscal One','601','G03','42000','one@test.local'),
 ('${id(71)}','${customer}','TEST010101BBB','Fiscal Two','601','G03','42001','two@test.local');`);
const invoicePayload={...payload(retail),requires_invoice:true,fiscal_profile_id:id(71),invoice_payment_form:'TRANSFER'};
await db.exec(`INSERT INTO public.customers(id,auth_user_id,name,email,phone)VALUES('${id(72)}','${outsider}','Other customer','other@test.local','123');
 INSERT INTO public.customer_fiscal_profiles(id,customer_id,rfc,legal_name,tax_regime,cfdi_use,fiscal_zip_code,billing_email)
 VALUES('${id(73)}','${id(72)}','TEST010101CCC','Foreign fiscal profile','601','G03','42002','other@test.local');`);
await fails(`SELECT public.create_priced_order('${JSON.stringify({...invoicePayload,fiscal_profile_id:id(73)})}'::jsonb)`,/perfil fiscal activo/);
await db.exec(`SELECT set_config('request.jwt.claim.sub','${agent}',false);SET ROLE authenticated;`);
const invoicedOrder=await scalar(`SELECT (public.create_priced_order('${JSON.stringify(invoicePayload)}'::jsonb)).id`);
await db.exec(`RESET ROLE;SELECT set_config('request.jwt.claim.sub','${admin}',false);`);
let invoice=await scalar(`SELECT invoice_details FROM public.sales_orders WHERE id='${invoicedOrder}'`);
assert.equal(invoice.legal_name,'Fiscal Two');assert.equal(invoice.issuer_zip_code,'42186');assert.equal(invoice.payment_form,'TRANSFER');
await db.exec(`UPDATE public.customer_fiscal_profiles SET legal_name='Later edited name' WHERE id='${id(71)}';UPDATE public.sales_orders SET admin_comments='Keep snapshot' WHERE id='${invoicedOrder}'`);
invoice=await scalar(`SELECT invoice_details FROM public.sales_orders WHERE id='${invoicedOrder}'`);
assert.equal(invoice.legal_name,'Fiscal Two','later profile edits do not change the invoice snapshot');
await db.exec(`UPDATE public.sales_orders SET status='SHIPPED' WHERE id='${invoicedOrder}'`);
await fails(`UPDATE public.sales_orders SET invoice_payment_form='CASH' WHERE id='${invoicedOrder}'`,/despu\u00e9s del env\u00edo/);
const beforeBadInvoice=Number(await scalar('SELECT count(*) FROM public.sales_orders'));
await fails(`SELECT public.create_priced_order('${JSON.stringify({...invoicePayload,fiscal_profile_id:id(999)})}'::jsonb)`,/perfil fiscal activo/);
await fails(`SELECT public.create_priced_order('${JSON.stringify({...invoicePayload,invoice_payment_form:'CREDITO'})}'::jsonb)`,/forma de pago/);
assert.equal(Number(await scalar('SELECT count(*) FROM public.sales_orders')),beforeBadInvoice,'invalid invoices roll back the complete order');
await db.exec(`UPDATE public.customer_fiscal_profiles SET is_active=false WHERE id='${id(71)}'`);
await fails(`SELECT public.create_priced_order('${JSON.stringify(invoicePayload)}'::jsonb)`,/perfil fiscal activo/);
await db.exec(`SELECT set_config('request.jwt.claim.sub','${customerUser}',false);SET ROLE authenticated;`);
const ownInvoice=await scalar(`SELECT (public.create_priced_order('${JSON.stringify({...invoicePayload,fiscal_profile_id:id(70),warehouse_id:undefined,price_list_id:undefined})}'::jsonb)).id`);
assert.equal(await scalar(`SELECT requires_invoice FROM public.sales_orders WHERE id='${ownInvoice}'`),true,'customer can choose their own fiscal information');
await db.exec('RESET ROLE');
console.log('PASS: invoice profile selection, issuer ZIP, customer creation, immutable snapshot, inactive profiles, invalid payment forms and atomic rollback');
await db.close();
